import pathlib
import uuid
import shutil
from simvue_integrations.connectors.moose import MooseRun

def moose_example(moose_app_path, run_folder) -> None:
    # Initialise the MooseRun class as a context manager
    with MooseRun() as run:
        
        # Initialise the run, providing a name for the run, and optionally extra information such as a folder, description, tags etc
        run.init(
            name="moose_simulation_thermal-%s" % str(uuid.uuid4()),
            description="An example of using the MooseRun Connector to track a MOOSE simulation.",
            folder=run_folder,
            tags=["moose", "thermal", "diffusion"],
        )

        # You can use any of the Simvue Run() methods to upload extra information before/after the simulation
        run.create_alert(
            name='avg_temp_above_500',
            source='metrics',
            metric='average_temerature',
            rule='is above',
            threshold=500.0,
            frequency=1,
            window=1,
            )
        
        # Then call the .launch() method to start your MOOSE simulation
        run.launch(
            moose_application_path=moose_app_path,
            moose_file_path=pathlib.Path(__file__).parent.joinpath("thermal_bar.i"),
            # These should match those defined in the Outputs section of the MOOSE file:
            output_dir_path=str(pathlib.Path(__file__).parent.joinpath("results")),
            results_prefix="simvue_thermal",
            # You can optionally choose to track VectorPostProcessor outputs too:
            track_vector_postprocessors = True,
            track_vector_positions = False,
        )

        # Once the simulation is complete, you can upload any final items to the Simvue run before it closes
        run.log_event("Deleting local copies of results...")
        # Delete local copies of results generated by this run, as these are all now stored by Simvue!
        shutil.rmtree(pathlib.Path(__file__).parent.joinpath("results"))
        
        return run.id
    
if __name__ == "__main__":
    moose_example(moose_app_path="/opt/moose/bin/moose-opt", run_folder="/moose_example")